apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-video-service
  namespace: hackathon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-video-service
  template:
    metadata:
      labels:
        app: hackathon-video-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: hackathon-video-service
          image: 905417995957.dkr.ecr.us-east-1.amazonaws.com/fiap-soat-g20/hackathon-video-service-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: hackathon-video-service-config
            - secretRef:
                name: hackathon-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/v1/health/readyz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/v1/health/livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
