apiVersion: v1
kind: Service
metadata:
  name: hackathon-video-service
  namespace: hackathon
spec:
  type: LoadBalancer # To run on cloud, or locally (http://localhost/api/v1/health)
  selector:
    app: hackathon-video-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30005
  # type: NodePort # To run locally
