apiVersion: v1
kind: ConfigMap
metadata:
  name: hackathon-video-manager-config
  namespace: hackathon
data:
  AUTH0_SCOPE: "openid profile email"
  AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
  AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}" # "fiapx-10soat-g21"
  APP_BASE_URL: "hackathon-video-service.hackathon.svc.cluster.local"
  API_PORT: "3000"